### ISSUE TITLE
About the SchemaBuilder docs and examples

### ISSUE THREAD

**Issue by evmek** [totaljs/examples#20]
Hi  Peter,
I am working with SchemaBuilder , I looked it (http://docs.totaljs.com/v1.7.x/en.html#api~Builders.SchemaBuilder. and https://github.com/totaljs/examples/tree/master/framework-schema-and-validation) 
but not understand some methods (rule,transform, workflow,compose) 

Maybe you can create a new example with use all methods.

Thanks,

**Comment by petersirka** [comment]
Hi @evmek,
yes, I will create some examples and I'll write some blogs. The SchemaBuilder is a really big cannon. I think that I'll write a new blog with Schema on next week.

BTW:
- __rule__ can store everything (variable, function, array, object, etc.), no more, no less it's a rule :-D
- __transform__ can transform the current model to other model
- __workflow__ can have a different actions (e.g. workflow send mail, logoff, etc.)
- __compose__ can compose the model from different values, e.g. you have the schema `article` and you need to pair article with its comments. And for this case is a composer.

Many features have same input/output arguments. The benefits are in an environment because SchemaBuilder offers error handling, custom options and asynchronous callbacks.

Simple example, controller:

```javascript
// User is a "SchemaBuilderEntity" in "Models" group.
exports.install = function() {
    F.route('/api/users/', json_user, ['post', 'json', '*Models/User']);
};

function json_user() {
    var self = this;
    // Below code solves errors and output.
    self.body.$async(self.callback()).$save().$workflow('notification');
}
```
I know, you have many questions. I will write blogs and examples about it.
Thanks.

**Comment by evmek** [comment]
Hi Peter,
Thanks for answer
I am wating for examples
