### ISSUE TITLE
TypeError: HTTP(...) is not a function TypeError: HTTP(...) is not a function

### ISSUE THREAD

**Issue by tablecell** [totaljs/examples#98]
```nodejs
require('total4');
ROUTE('GET /json', function() {
    
    this.json({ message:  ' world' });   // 
});
const options = {};

options.livereload = true;
HTTP('debug')(options);
```

how use  livereload  in single app.js ;  not in  Project structure mode  [index.js, controllers/default.js(exports.install) ]

**Comment by petersirka** [comment]
Hi @tablecell,
`livereload` is a special part of `debug` mode. You need to run Total.js under debug mode like `require('total4/debug')(options)` because the `debug` mode will run the app under another child process, and the main process will monitor all changes (that's a very important functionality for the LiveReload) in the project structure, and if `livereload` is `true`, then the main thread opens the HTTP server for LiveReload. So you can't do it in a single file.

I recommend to create a simple file structure:

```html
/definitions/app.js
index.js
```

or

```html
/modules/app.js
index.js
```

- download [`index.js`](https://github.com/totaljs/framework4/blob/master/helpers/index.js)
- create `app.js` with your logic
- and everything will work as you expected

**Comment by tablecell** [comment]
tks
